WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x111058710>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/ed1a4b462653c1ab7e23dccd0a6d84fb/element
WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x111059b50>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/ed1a4b462653c1ab7e23dccd0a6d84fb/element
WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11105aad0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/ed1a4b462653c1ab7e23dccd0a6d84fb/element
WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1110e9950>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/ed1a4b462653c1ab7e23dccd0a6d84fb
WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1110ea190>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/ed1a4b462653c1ab7e23dccd0a6d84fb
WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1110ea9d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/ed1a4b462653c1ab7e23dccd0a6d84fb
WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11103ec10>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/ed1a4b462653c1ab7e23dccd0a6d84fb
WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11103f7d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/ed1a4b462653c1ab7e23dccd0a6d84fb
WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11103fc90>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/ed1a4b462653c1ab7e23dccd0a6d84fb